name: Deploy Quiz.Authorization

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        id: building
        run: dotnet build Quiz.Authorization/Quiz.Authorization.csproj --configuration Release
      - name: List builded files
        run: ls
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "Quiz.Authorization/bin/Release/netcoreapp3.1/*"
          target: "Quiz.Authorization.Builded"
      - name: Set connection string to Env variables 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: export datebaseconnectionstring="2223333"

      - name: Downloading service-check script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: wget "https://raw.githubusercontent.com/OneZeroZeroOneOne/Quiz.Authorization/main/service-check" -O "/root/service-check"
      - name: Giving rights for service check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: chmod +rx "/root/service-check"
      - name: Starting service-check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /root/service-check quiz-authorization.service
