name: Deploy Quiz.Authorization

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
	uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        id: building
        run: dotnet build Quiz.Authorization.csproj